// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 0.1.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['nedelec.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_1e7b188ba5b2a0548504cad148255ba9d1ff10f5;

extern ufc_finite_element element_cb15d806737b06fdda339e0a558cac340bf163aa;

extern ufc_finite_element element_7a6f94d9f714280d462314e33f6c4b34aa230353;

extern ufc_dofmap dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5;

extern ufc_dofmap dofmap_cb15d806737b06fdda339e0a558cac340bf163aa;

extern ufc_dofmap dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353;

extern ufc_integral integral_cell_otherwise_2af0ba280175e3004e2c7b59d02851fa183ce88d;

extern ufc_form form_2af0ba280175e3004e2c7b59d02851fa183ce88d;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_nedelec_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_nedelec_a(const char* function_name);

#ifdef __cplusplus
}
#endif
