// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 0.1.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['nedelec.ufl'],
//   'verbosity': 30,
//   'visualise': False}

typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_1e7b188ba5b2a0548504cad148255ba9d1ff10f5

ufc_finite_element element_1e7b188ba5b2a0548504cad148255ba9d1ff10f5 = {.signature = "FiniteElement('Lagrange', tetrahedron, 1)",
                                                                       .cell_shape = tetrahedron,
                                                                       .topological_dimension = 3,
                                                                       .geometric_dimension = 3,
                                                                       .space_dimension = 4,
                                                                       .value_rank = 0,
                                                                       .value_shape = NULL,
                                                                       .value_size = 1,
                                                                       .reference_value_rank = 0,
                                                                       .reference_value_shape = NULL,
                                                                       .reference_value_size = 1,
                                                                       .degree = 1,
                                                                       .family = "Lagrange",
                                                                       .block_size = 1,

                                                                       .needs_transformation_data = 0,
                                                                       .interpolation_is_identity = 1,

                                                                       .num_sub_elements = 0,
                                                                       .sub_elements = NULL};

// End of code for element element_1e7b188ba5b2a0548504cad148255ba9d1ff10f5

// Code for element element_cb15d806737b06fdda339e0a558cac340bf163aa

int value_shape_element_cb15d806737b06fdda339e0a558cac340bf163aa[1] = {3};
int reference_value_shape_element_cb15d806737b06fdda339e0a558cac340bf163aa[1] = {3};
ufc_finite_element *sub_elements_element_cb15d806737b06fdda339e0a558cac340bf163aa[3] = {&element_1e7b188ba5b2a0548504cad148255ba9d1ff10f5,
                                                                                        &element_1e7b188ba5b2a0548504cad148255ba9d1ff10f5,
                                                                                        &element_1e7b188ba5b2a0548504cad148255ba9d1ff10f5};

ufc_finite_element element_cb15d806737b06fdda339e0a558cac340bf163aa = {
    .signature = "VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
    .cell_shape = tetrahedron,
    .topological_dimension = 3,
    .geometric_dimension = 3,
    .space_dimension = 12,
    .value_rank = 1,
    .value_shape = value_shape_element_cb15d806737b06fdda339e0a558cac340bf163aa,
    .value_size = 3,
    .reference_value_rank = 1,
    .reference_value_shape = reference_value_shape_element_cb15d806737b06fdda339e0a558cac340bf163aa,
    .reference_value_size = 3,
    .degree = 1,
    .family = "Lagrange",
    .block_size = 3,

    .needs_transformation_data = 0,
    .interpolation_is_identity = 1,

    .num_sub_elements = 3,
    .sub_elements = sub_elements_element_cb15d806737b06fdda339e0a558cac340bf163aa};

// End of code for element element_cb15d806737b06fdda339e0a558cac340bf163aa

// Code for element element_7a6f94d9f714280d462314e33f6c4b34aa230353

int value_shape_element_7a6f94d9f714280d462314e33f6c4b34aa230353[1] = {3};
int reference_value_shape_element_7a6f94d9f714280d462314e33f6c4b34aa230353[1] = {3};

ufc_finite_element element_7a6f94d9f714280d462314e33f6c4b34aa230353 = {
    .signature = "FiniteElement('Nedelec 1st kind H(curl)', tetrahedron, 1)",
    .cell_shape = tetrahedron,
    .topological_dimension = 3,
    .geometric_dimension = 3,
    .space_dimension = 6,
    .value_rank = 1,
    .value_shape = value_shape_element_7a6f94d9f714280d462314e33f6c4b34aa230353,
    .value_size = 3,
    .reference_value_rank = 1,
    .reference_value_shape = reference_value_shape_element_7a6f94d9f714280d462314e33f6c4b34aa230353,
    .reference_value_size = 3,
    .degree = 1,
    .family = "Nedelec 1st kind H(curl)",
    .block_size = 1,

    .needs_transformation_data = 1,
    .interpolation_is_identity = 0,

    .num_sub_elements = 0,
    .sub_elements = NULL};

// End of code for element element_7a6f94d9f714280d462314e33f6c4b34aa230353

// Code for dofmap dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5

void tabulate_entity_dofs_dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5(int *restrict dofs, int d,
                                                                          int i)
{
  switch (d)
  {
  case 0:
    switch (i)
    {
    case 0:
      dofs[0] = 0;
      break;
    case 1:
      dofs[0] = 1;
      break;
    case 2:
      dofs[0] = 2;
      break;
    case 3:
      dofs[0] = 3;
      break;
    }
    break;
  }
}

ufc_dofmap dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5 = {.signature = "FFCX dofmap for FiniteElement('Lagrange', tetrahedron, 1)",
                                                              .block_size = 1,
                                                              .num_global_support_dofs = 0,
                                                              .num_element_support_dofs = 4,
                                                              .num_entity_dofs[0] = 1,
                                                              .num_entity_dofs[1] = 0,
                                                              .num_entity_dofs[2] = 0,
                                                              .num_entity_dofs[3] = 0,
                                                              .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5,
                                                              .num_sub_dofmaps = 0,
                                                              .sub_dofmaps = NULL};

// End of code for dofmap dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5

// Code for dofmap dofmap_cb15d806737b06fdda339e0a558cac340bf163aa

ufc_dofmap *sub_dofmaps_dofmap_cb15d806737b06fdda339e0a558cac340bf163aa[3] = {&dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5,
                                                                              &dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5,
                                                                              &dofmap_1e7b188ba5b2a0548504cad148255ba9d1ff10f5};

void tabulate_entity_dofs_dofmap_cb15d806737b06fdda339e0a558cac340bf163aa(int *restrict dofs, int d,
                                                                          int i)
{
  switch (d)
  {
  case 0:
    switch (i)
    {
    case 0:
      dofs[0] = 0;
      break;
    case 1:
      dofs[0] = 1;
      break;
    case 2:
      dofs[0] = 2;
      break;
    case 3:
      dofs[0] = 3;
      break;
    }
    break;
  }
}

ufc_dofmap dofmap_cb15d806737b06fdda339e0a558cac340bf163aa = {
    .signature = "FFCX dofmap for VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
    .block_size = 3,
    .num_global_support_dofs = 0,
    .num_element_support_dofs = 4,
    .num_entity_dofs[0] = 1,
    .num_entity_dofs[1] = 0,
    .num_entity_dofs[2] = 0,
    .num_entity_dofs[3] = 0,
    .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_cb15d806737b06fdda339e0a558cac340bf163aa,
    .num_sub_dofmaps = 3,
    .sub_dofmaps = sub_dofmaps_dofmap_cb15d806737b06fdda339e0a558cac340bf163aa};

// End of code for dofmap dofmap_cb15d806737b06fdda339e0a558cac340bf163aa

// Code for dofmap dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353

void tabulate_entity_dofs_dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353(int *restrict dofs, int d,
                                                                          int i)
{
  switch (d)
  {
  case 1:
    switch (i)
    {
    case 0:
      dofs[0] = 0;
      break;
    case 1:
      dofs[0] = 1;
      break;
    case 2:
      dofs[0] = 2;
      break;
    case 3:
      dofs[0] = 3;
      break;
    case 4:
      dofs[0] = 4;
      break;
    case 5:
      dofs[0] = 5;
      break;
    }
    break;
  }
}

ufc_dofmap dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353 = {.signature = "FFCX dofmap for FiniteElement('Nedelec 1st kind H(curl)', tetrahedron, 1)",
                                                              .block_size = 1,
                                                              .num_global_support_dofs = 0,
                                                              .num_element_support_dofs = 6,
                                                              .num_entity_dofs[0] = 0,
                                                              .num_entity_dofs[1] = 1,
                                                              .num_entity_dofs[2] = 0,
                                                              .num_entity_dofs[3] = 0,
                                                              .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353,
                                                              .num_sub_dofmaps = 0,
                                                              .sub_dofmaps = NULL};

// End of code for dofmap dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353

// Code for integral integral_cell_otherwise_2af0ba280175e3004e2c7b59d02851fa183ce88d

void tabulate_tensor_integral_cell_otherwise_2af0ba280175e3004e2c7b59d02851fa183ce88d(
    ufc_scalar_t *restrict A, const ufc_scalar_t *restrict w, const ufc_scalar_t *restrict c,
    const double *restrict coordinate_dofs, const int *restrict entity_local_index,
    const uint8_t *restrict quadrature_permutation, const uint32_t cell_permutation)
{
  // Quadrature rules
  static const double weights_421[1] = {0.1666666666666667};
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  double FE27_C0_D001_Q421[1][1][1][6] = {{{{0.0, -1.0, 0.0, 1.0, 0.0, -1.0}}}};
  {
    double t0 = 0;
    if ((cell_permutation & 1 << 12) != 0)
    {
      t0 = FE27_C0_D001_Q421[0][0][0][0];
      FE27_C0_D001_Q421[0][0][0][0] = -t0;
    }
    if ((cell_permutation & 1 << 13) != 0)
    {
      t0 = FE27_C0_D001_Q421[0][0][0][1];
      FE27_C0_D001_Q421[0][0][0][1] = -t0;
    }
    if ((cell_permutation & 1 << 14) != 0)
    {
      t0 = FE27_C0_D001_Q421[0][0][0][2];
      FE27_C0_D001_Q421[0][0][0][2] = -t0;
    }
    if ((cell_permutation & 1 << 15) != 0)
    {
      t0 = FE27_C0_D001_Q421[0][0][0][3];
      FE27_C0_D001_Q421[0][0][0][3] = -t0;
    }
    if ((cell_permutation & 1 << 16) != 0)
    {
      t0 = FE27_C0_D001_Q421[0][0][0][4];
      FE27_C0_D001_Q421[0][0][0][4] = -t0;
    }
    if ((cell_permutation & 1 << 17) != 0)
    {
      t0 = FE27_C0_D001_Q421[0][0][0][5];
      FE27_C0_D001_Q421[0][0][0][5] = -t0;
    }
  }
  double FE27_C0_D010_Q421[1][1][1][6] = {{{{0.0, 0.0, -1.0, 0.0, 1.0, -1.0}}}};
  {
    double t0 = 0;
    if ((cell_permutation & 1 << 12) != 0)
    {
      t0 = FE27_C0_D010_Q421[0][0][0][0];
      FE27_C0_D010_Q421[0][0][0][0] = -t0;
    }
    if ((cell_permutation & 1 << 13) != 0)
    {
      t0 = FE27_C0_D010_Q421[0][0][0][1];
      FE27_C0_D010_Q421[0][0][0][1] = -t0;
    }
    if ((cell_permutation & 1 << 14) != 0)
    {
      t0 = FE27_C0_D010_Q421[0][0][0][2];
      FE27_C0_D010_Q421[0][0][0][2] = -t0;
    }
    if ((cell_permutation & 1 << 15) != 0)
    {
      t0 = FE27_C0_D010_Q421[0][0][0][3];
      FE27_C0_D010_Q421[0][0][0][3] = -t0;
    }
    if ((cell_permutation & 1 << 16) != 0)
    {
      t0 = FE27_C0_D010_Q421[0][0][0][4];
      FE27_C0_D010_Q421[0][0][0][4] = -t0;
    }
    if ((cell_permutation & 1 << 17) != 0)
    {
      t0 = FE27_C0_D010_Q421[0][0][0][5];
      FE27_C0_D010_Q421[0][0][0][5] = -t0;
    }
  }
  double FE27_C1_D001_Q421[1][1][1][6] = {{{{-1.0, 0.0, 0.0, 1.0, -1.0, 0.0}}}};
  {
    double t0 = 0;
    if ((cell_permutation & 1 << 12) != 0)
    {
      t0 = FE27_C1_D001_Q421[0][0][0][0];
      FE27_C1_D001_Q421[0][0][0][0] = -t0;
    }
    if ((cell_permutation & 1 << 13) != 0)
    {
      t0 = FE27_C1_D001_Q421[0][0][0][1];
      FE27_C1_D001_Q421[0][0][0][1] = -t0;
    }
    if ((cell_permutation & 1 << 14) != 0)
    {
      t0 = FE27_C1_D001_Q421[0][0][0][2];
      FE27_C1_D001_Q421[0][0][0][2] = -t0;
    }
    if ((cell_permutation & 1 << 15) != 0)
    {
      t0 = FE27_C1_D001_Q421[0][0][0][3];
      FE27_C1_D001_Q421[0][0][0][3] = -t0;
    }
    if ((cell_permutation & 1 << 16) != 0)
    {
      t0 = FE27_C1_D001_Q421[0][0][0][4];
      FE27_C1_D001_Q421[0][0][0][4] = -t0;
    }
    if ((cell_permutation & 1 << 17) != 0)
    {
      t0 = FE27_C1_D001_Q421[0][0][0][5];
      FE27_C1_D001_Q421[0][0][0][5] = -t0;
    }
  }
  double FE27_C1_D100_Q421[1][1][1][6] = {{{{0.0, 0.0, 1.0, 0.0, -1.0, 1.0}}}};
  {
    double t0 = 0;
    if ((cell_permutation & 1 << 12) != 0)
    {
      t0 = FE27_C1_D100_Q421[0][0][0][0];
      FE27_C1_D100_Q421[0][0][0][0] = -t0;
    }
    if ((cell_permutation & 1 << 13) != 0)
    {
      t0 = FE27_C1_D100_Q421[0][0][0][1];
      FE27_C1_D100_Q421[0][0][0][1] = -t0;
    }
    if ((cell_permutation & 1 << 14) != 0)
    {
      t0 = FE27_C1_D100_Q421[0][0][0][2];
      FE27_C1_D100_Q421[0][0][0][2] = -t0;
    }
    if ((cell_permutation & 1 << 15) != 0)
    {
      t0 = FE27_C1_D100_Q421[0][0][0][3];
      FE27_C1_D100_Q421[0][0][0][3] = -t0;
    }
    if ((cell_permutation & 1 << 16) != 0)
    {
      t0 = FE27_C1_D100_Q421[0][0][0][4];
      FE27_C1_D100_Q421[0][0][0][4] = -t0;
    }
    if ((cell_permutation & 1 << 17) != 0)
    {
      t0 = FE27_C1_D100_Q421[0][0][0][5];
      FE27_C1_D100_Q421[0][0][0][5] = -t0;
    }
  }
  double FE27_C2_D010_Q421[1][1][1][6] = {{{{1.0, 0.0, 0.0, -1.0, 1.0, 0.0}}}};
  {
    double t0 = 0;
    if ((cell_permutation & 1 << 12) != 0)
    {
      t0 = FE27_C2_D010_Q421[0][0][0][0];
      FE27_C2_D010_Q421[0][0][0][0] = -t0;
    }
    if ((cell_permutation & 1 << 13) != 0)
    {
      t0 = FE27_C2_D010_Q421[0][0][0][1];
      FE27_C2_D010_Q421[0][0][0][1] = -t0;
    }
    if ((cell_permutation & 1 << 14) != 0)
    {
      t0 = FE27_C2_D010_Q421[0][0][0][2];
      FE27_C2_D010_Q421[0][0][0][2] = -t0;
    }
    if ((cell_permutation & 1 << 15) != 0)
    {
      t0 = FE27_C2_D010_Q421[0][0][0][3];
      FE27_C2_D010_Q421[0][0][0][3] = -t0;
    }
    if ((cell_permutation & 1 << 16) != 0)
    {
      t0 = FE27_C2_D010_Q421[0][0][0][4];
      FE27_C2_D010_Q421[0][0][0][4] = -t0;
    }
    if ((cell_permutation & 1 << 17) != 0)
    {
      t0 = FE27_C2_D010_Q421[0][0][0][5];
      FE27_C2_D010_Q421[0][0][0][5] = -t0;
    }
  }
  double FE27_C2_D100_Q421[1][1][1][6] = {{{{0.0, 1.0, 0.0, -1.0, 0.0, 1.0}}}};
  {
    double t0 = 0;
    if ((cell_permutation & 1 << 12) != 0)
    {
      t0 = FE27_C2_D100_Q421[0][0][0][0];
      FE27_C2_D100_Q421[0][0][0][0] = -t0;
    }
    if ((cell_permutation & 1 << 13) != 0)
    {
      t0 = FE27_C2_D100_Q421[0][0][0][1];
      FE27_C2_D100_Q421[0][0][0][1] = -t0;
    }
    if ((cell_permutation & 1 << 14) != 0)
    {
      t0 = FE27_C2_D100_Q421[0][0][0][2];
      FE27_C2_D100_Q421[0][0][0][2] = -t0;
    }
    if ((cell_permutation & 1 << 15) != 0)
    {
      t0 = FE27_C2_D100_Q421[0][0][0][3];
      FE27_C2_D100_Q421[0][0][0][3] = -t0;
    }
    if ((cell_permutation & 1 << 16) != 0)
    {
      t0 = FE27_C2_D100_Q421[0][0][0][4];
      FE27_C2_D100_Q421[0][0][0][4] = -t0;
    }
    if ((cell_permutation & 1 << 17) != 0)
    {
      t0 = FE27_C2_D100_Q421[0][0][0][5];
      FE27_C2_D100_Q421[0][0][0][5] = -t0;
    }
  }
  static const double FE9_C0_D001_Q421[1][1][1][4] = {{{{-1.0, 0.0, 0.0, 1.0}}}};
  static const double FE9_C0_D010_Q421[1][1][1][4] = {{{{-1.0, 0.0, 1.0, 0.0}}}};
  static const double FE9_C0_D100_Q421[1][1][1][4] = {{{{-1.0, 1.0, 0.0, 0.0}}}};
  // Quadrature loop independent computations for quadrature rule 421
  const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Q421[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D100_Q421[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D100_Q421[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D100_Q421[0][0][0][3];
  const double J_c4 = coordinate_dofs[1] * FE9_C0_D010_Q421[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D010_Q421[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D010_Q421[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D010_Q421[0][0][0][3];
  const double J_c1 = coordinate_dofs[0] * FE9_C0_D010_Q421[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D010_Q421[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D010_Q421[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D010_Q421[0][0][0][3];
  const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Q421[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D100_Q421[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D100_Q421[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D100_Q421[0][0][0][3];
  const double J_c8 = coordinate_dofs[2] * FE9_C0_D001_Q421[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D001_Q421[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D001_Q421[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D001_Q421[0][0][0][3];
  const double J_c5 = coordinate_dofs[1] * FE9_C0_D001_Q421[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D001_Q421[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D001_Q421[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D001_Q421[0][0][0][3];
  const double J_c7 = coordinate_dofs[2] * FE9_C0_D010_Q421[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D010_Q421[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D010_Q421[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D010_Q421[0][0][0][3];
  const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Q421[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D100_Q421[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D100_Q421[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D100_Q421[0][0][0][3];
  const double J_c2 = coordinate_dofs[0] * FE9_C0_D001_Q421[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D001_Q421[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D001_Q421[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D001_Q421[0][0][0][3];
  ufc_scalar_t sp_421[206];
  sp_421[0] = J_c0 * J_c4;
  sp_421[1] = J_c1 * J_c3;
  sp_421[2] = sp_421[0] + -1 * sp_421[1];
  sp_421[3] = J_c4 * J_c8;
  sp_421[4] = J_c5 * J_c7;
  sp_421[5] = sp_421[3] + -1 * sp_421[4];
  sp_421[6] = J_c0 * sp_421[5];
  sp_421[7] = J_c5 * J_c6;
  sp_421[8] = J_c3 * J_c8;
  sp_421[9] = sp_421[7] + -1 * sp_421[8];
  sp_421[10] = J_c1 * sp_421[9];
  sp_421[11] = sp_421[6] + sp_421[10];
  sp_421[12] = J_c3 * J_c7;
  sp_421[13] = J_c4 * J_c6;
  sp_421[14] = sp_421[12] + -1 * sp_421[13];
  sp_421[15] = J_c2 * sp_421[14];
  sp_421[16] = sp_421[11] + sp_421[15];
  sp_421[17] = sp_421[2] / sp_421[16];
  sp_421[18] = J_c2 * J_c3;
  sp_421[19] = J_c0 * J_c5;
  sp_421[20] = sp_421[18] + -1 * sp_421[19];
  sp_421[21] = sp_421[20] / sp_421[16];
  sp_421[22] = sp_421[5] / sp_421[16];
  sp_421[23] = sp_421[17] * sp_421[22];
  sp_421[24] = sp_421[21] * sp_421[22];
  sp_421[25] = J_c1 * J_c5;
  sp_421[26] = J_c2 * J_c4;
  sp_421[27] = sp_421[25] + -1 * sp_421[26];
  sp_421[28] = sp_421[27] / sp_421[16];
  sp_421[29] = J_c3 * (-1 * J_c8);
  sp_421[30] = sp_421[7] + sp_421[29];
  sp_421[31] = sp_421[30] / sp_421[16];
  sp_421[32] = sp_421[17] * sp_421[31];
  sp_421[33] = sp_421[28] * sp_421[31];
  sp_421[34] = sp_421[14] / sp_421[16];
  sp_421[35] = sp_421[28] * sp_421[34];
  sp_421[36] = sp_421[21] * sp_421[34];
  sp_421[37] = -1 * sp_421[35] + sp_421[23];
  sp_421[38] = -1 * sp_421[33] + sp_421[24];
  sp_421[39] = -1 * sp_421[36] + sp_421[32];
  sp_421[40] = -1 * sp_421[24] + sp_421[33];
  sp_421[41] = -1 * sp_421[23] + sp_421[35];
  sp_421[42] = -1 * sp_421[32] + sp_421[36];
  sp_421[43] = sp_421[37] * sp_421[37];
  sp_421[44] = sp_421[37] * sp_421[38];
  sp_421[45] = sp_421[37] * sp_421[39];
  sp_421[46] = sp_421[37] * sp_421[40];
  sp_421[47] = sp_421[41] * sp_421[37];
  sp_421[48] = sp_421[42] * sp_421[37];
  sp_421[49] = sp_421[38] * sp_421[38];
  sp_421[50] = sp_421[38] * sp_421[39];
  sp_421[51] = sp_421[38] * sp_421[40];
  sp_421[52] = sp_421[41] * sp_421[38];
  sp_421[53] = sp_421[42] * sp_421[38];
  sp_421[54] = sp_421[39] * sp_421[39];
  sp_421[55] = sp_421[39] * sp_421[40];
  sp_421[56] = sp_421[41] * sp_421[39];
  sp_421[57] = sp_421[42] * sp_421[39];
  sp_421[58] = sp_421[40] * sp_421[40];
  sp_421[59] = sp_421[41] * sp_421[40];
  sp_421[60] = sp_421[42] * sp_421[40];
  sp_421[61] = sp_421[41] * sp_421[41];
  sp_421[62] = sp_421[41] * sp_421[42];
  sp_421[63] = sp_421[42] * sp_421[42];
  sp_421[64] = J_c0 * J_c8;
  sp_421[65] = J_c6 * (-1 * J_c2);
  sp_421[66] = sp_421[64] + sp_421[65];
  sp_421[67] = sp_421[66] / sp_421[16];
  sp_421[68] = J_c1 * J_c6;
  sp_421[69] = J_c0 * J_c7;
  sp_421[70] = sp_421[68] + -1 * sp_421[69];
  sp_421[71] = sp_421[70] / sp_421[16];
  sp_421[72] = sp_421[28] * sp_421[71];
  sp_421[73] = sp_421[67] * sp_421[28];
  sp_421[74] = J_c2 * J_c7;
  sp_421[75] = J_c8 * (-1 * J_c1);
  sp_421[76] = sp_421[74] + sp_421[75];
  sp_421[77] = sp_421[76] / sp_421[16];
  sp_421[78] = sp_421[21] * sp_421[71];
  sp_421[79] = sp_421[77] * sp_421[21];
  sp_421[80] = sp_421[77] * sp_421[17];
  sp_421[81] = sp_421[67] * sp_421[17];
  sp_421[82] = -1 * sp_421[80] + sp_421[72];
  sp_421[83] = -1 * sp_421[79] + sp_421[73];
  sp_421[84] = -1 * sp_421[81] + sp_421[78];
  sp_421[85] = -1 * sp_421[73] + sp_421[79];
  sp_421[86] = -1 * sp_421[72] + sp_421[80];
  sp_421[87] = -1 * sp_421[78] + sp_421[81];
  sp_421[88] = sp_421[82] * sp_421[82];
  sp_421[89] = sp_421[83] * sp_421[82];
  sp_421[90] = sp_421[82] * sp_421[84];
  sp_421[91] = sp_421[85] * sp_421[82];
  sp_421[92] = sp_421[86] * sp_421[82];
  sp_421[93] = sp_421[87] * sp_421[82];
  sp_421[94] = sp_421[83] * sp_421[83];
  sp_421[95] = sp_421[83] * sp_421[84];
  sp_421[96] = sp_421[83] * sp_421[85];
  sp_421[97] = sp_421[86] * sp_421[83];
  sp_421[98] = sp_421[87] * sp_421[83];
  sp_421[99] = sp_421[84] * sp_421[84];
  sp_421[100] = sp_421[85] * sp_421[84];
  sp_421[101] = sp_421[86] * sp_421[84];
  sp_421[102] = sp_421[87] * sp_421[84];
  sp_421[103] = sp_421[85] * sp_421[85];
  sp_421[104] = sp_421[86] * sp_421[85];
  sp_421[105] = sp_421[87] * sp_421[85];
  sp_421[106] = sp_421[86] * sp_421[86];
  sp_421[107] = sp_421[86] * sp_421[87];
  sp_421[108] = sp_421[87] * sp_421[87];
  sp_421[109] = sp_421[88] + sp_421[43];
  sp_421[110] = sp_421[89] + sp_421[44];
  sp_421[111] = sp_421[90] + sp_421[45];
  sp_421[112] = sp_421[91] + sp_421[46];
  sp_421[113] = sp_421[92] + sp_421[47];
  sp_421[114] = sp_421[93] + sp_421[48];
  sp_421[115] = sp_421[94] + sp_421[49];
  sp_421[116] = sp_421[95] + sp_421[50];
  sp_421[117] = sp_421[96] + sp_421[51];
  sp_421[118] = sp_421[97] + sp_421[52];
  sp_421[119] = sp_421[98] + sp_421[53];
  sp_421[120] = sp_421[99] + sp_421[54];
  sp_421[121] = sp_421[100] + sp_421[55];
  sp_421[122] = sp_421[101] + sp_421[56];
  sp_421[123] = sp_421[102] + sp_421[57];
  sp_421[124] = sp_421[103] + sp_421[58];
  sp_421[125] = sp_421[104] + sp_421[59];
  sp_421[126] = sp_421[105] + sp_421[60];
  sp_421[127] = sp_421[106] + sp_421[61];
  sp_421[128] = sp_421[107] + sp_421[62];
  sp_421[129] = sp_421[108] + sp_421[63];
  sp_421[130] = sp_421[77] * sp_421[34];
  sp_421[131] = sp_421[77] * sp_421[31];
  sp_421[132] = sp_421[67] * sp_421[34];
  sp_421[133] = sp_421[67] * sp_421[22];
  sp_421[134] = sp_421[71] * sp_421[22];
  sp_421[135] = sp_421[71] * sp_421[31];
  sp_421[136] = -1 * sp_421[134] + sp_421[130];
  sp_421[137] = -1 * sp_421[133] + sp_421[131];
  sp_421[138] = -1 * sp_421[135] + sp_421[132];
  sp_421[139] = -1 * sp_421[131] + sp_421[133];
  sp_421[140] = -1 * sp_421[130] + sp_421[134];
  sp_421[141] = -1 * sp_421[132] + sp_421[135];
  sp_421[142] = sp_421[136] * sp_421[136];
  sp_421[143] = sp_421[136] * sp_421[137];
  sp_421[144] = sp_421[136] * sp_421[138];
  sp_421[145] = sp_421[136] * sp_421[139];
  sp_421[146] = sp_421[136] * sp_421[140];
  sp_421[147] = sp_421[136] * sp_421[141];
  sp_421[148] = sp_421[137] * sp_421[137];
  sp_421[149] = sp_421[138] * sp_421[137];
  sp_421[150] = sp_421[139] * sp_421[137];
  sp_421[151] = sp_421[140] * sp_421[137];
  sp_421[152] = sp_421[137] * sp_421[141];
  sp_421[153] = sp_421[138] * sp_421[138];
  sp_421[154] = sp_421[138] * sp_421[139];
  sp_421[155] = sp_421[138] * sp_421[140];
  sp_421[156] = sp_421[138] * sp_421[141];
  sp_421[157] = sp_421[139] * sp_421[139];
  sp_421[158] = sp_421[139] * sp_421[140];
  sp_421[159] = sp_421[139] * sp_421[141];
  sp_421[160] = sp_421[140] * sp_421[140];
  sp_421[161] = sp_421[140] * sp_421[141];
  sp_421[162] = sp_421[141] * sp_421[141];
  sp_421[163] = sp_421[109] + sp_421[142];
  sp_421[164] = sp_421[110] + sp_421[143];
  sp_421[165] = sp_421[111] + sp_421[144];
  sp_421[166] = sp_421[112] + sp_421[145];
  sp_421[167] = sp_421[113] + sp_421[146];
  sp_421[168] = sp_421[114] + sp_421[147];
  sp_421[169] = sp_421[115] + sp_421[148];
  sp_421[170] = sp_421[116] + sp_421[149];
  sp_421[171] = sp_421[117] + sp_421[150];
  sp_421[172] = sp_421[118] + sp_421[151];
  sp_421[173] = sp_421[119] + sp_421[152];
  sp_421[174] = sp_421[120] + sp_421[153];
  sp_421[175] = sp_421[121] + sp_421[154];
  sp_421[176] = sp_421[122] + sp_421[155];
  sp_421[177] = sp_421[123] + sp_421[156];
  sp_421[178] = sp_421[124] + sp_421[157];
  sp_421[179] = sp_421[125] + sp_421[158];
  sp_421[180] = sp_421[126] + sp_421[159];
  sp_421[181] = sp_421[127] + sp_421[160];
  sp_421[182] = sp_421[128] + sp_421[161];
  sp_421[183] = sp_421[129] + sp_421[162];
  sp_421[184] = fabs(sp_421[16]);
  sp_421[185] = sp_421[163] * sp_421[184];
  sp_421[186] = sp_421[164] * sp_421[184];
  sp_421[187] = sp_421[165] * sp_421[184];
  sp_421[188] = sp_421[166] * sp_421[184];
  sp_421[189] = sp_421[167] * sp_421[184];
  sp_421[190] = sp_421[168] * sp_421[184];
  sp_421[191] = sp_421[169] * sp_421[184];
  sp_421[192] = sp_421[170] * sp_421[184];
  sp_421[193] = sp_421[171] * sp_421[184];
  sp_421[194] = sp_421[172] * sp_421[184];
  sp_421[195] = sp_421[173] * sp_421[184];
  sp_421[196] = sp_421[174] * sp_421[184];
  sp_421[197] = sp_421[175] * sp_421[184];
  sp_421[198] = sp_421[176] * sp_421[184];
  sp_421[199] = sp_421[177] * sp_421[184];
  sp_421[200] = sp_421[178] * sp_421[184];
  sp_421[201] = sp_421[179] * sp_421[184];
  sp_421[202] = sp_421[180] * sp_421[184];
  sp_421[203] = sp_421[181] * sp_421[184];
  sp_421[204] = sp_421[182] * sp_421[184];
  sp_421[205] = sp_421[183] * sp_421[184];
  for (int iq = 0; iq < 1; ++iq)
  {
    const ufc_scalar_t fw0 = sp_421[191] * weights_421[iq];
    const ufc_scalar_t fw1 = sp_421[186] * weights_421[iq];
    const ufc_scalar_t fw2 = sp_421[193] * weights_421[iq];
    const ufc_scalar_t fw3 = sp_421[192] * weights_421[iq];
    const ufc_scalar_t fw4 = sp_421[194] * weights_421[iq];
    const ufc_scalar_t fw5 = sp_421[195] * weights_421[iq];
    const ufc_scalar_t fw6 = sp_421[185] * weights_421[iq];
    const ufc_scalar_t fw7 = sp_421[188] * weights_421[iq];
    const ufc_scalar_t fw8 = sp_421[187] * weights_421[iq];
    const ufc_scalar_t fw9 = sp_421[189] * weights_421[iq];
    const ufc_scalar_t fw10 = sp_421[190] * weights_421[iq];
    const ufc_scalar_t fw11 = sp_421[200] * weights_421[iq];
    const ufc_scalar_t fw12 = sp_421[197] * weights_421[iq];
    const ufc_scalar_t fw13 = sp_421[201] * weights_421[iq];
    const ufc_scalar_t fw14 = sp_421[202] * weights_421[iq];
    const ufc_scalar_t fw15 = sp_421[196] * weights_421[iq];
    const ufc_scalar_t fw16 = sp_421[198] * weights_421[iq];
    const ufc_scalar_t fw17 = sp_421[199] * weights_421[iq];
    const ufc_scalar_t fw18 = sp_421[203] * weights_421[iq];
    const ufc_scalar_t fw19 = sp_421[204] * weights_421[iq];
    const ufc_scalar_t fw20 = sp_421[205] * weights_421[iq];
    for (int i = 0; i < 6; ++i)
    {
      for (int j = 0; j < 6; ++j)
      {
        A[6 * i + j] += fw0 * FE27_C0_D010_Q421[0][0][0][i] * FE27_C0_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw1 * FE27_C0_D010_Q421[0][0][0][i] * FE27_C0_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw2 * FE27_C0_D010_Q421[0][0][0][i] * FE27_C1_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw3 * FE27_C0_D010_Q421[0][0][0][i] * FE27_C1_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw4 * FE27_C0_D010_Q421[0][0][0][i] * FE27_C2_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw5 * FE27_C0_D010_Q421[0][0][0][i] * FE27_C2_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw1 * FE27_C0_D001_Q421[0][0][0][i] * FE27_C0_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw6 * FE27_C0_D001_Q421[0][0][0][i] * FE27_C0_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw7 * FE27_C0_D001_Q421[0][0][0][i] * FE27_C1_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw8 * FE27_C0_D001_Q421[0][0][0][i] * FE27_C1_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw9 * FE27_C0_D001_Q421[0][0][0][i] * FE27_C2_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw10 * FE27_C0_D001_Q421[0][0][0][i] * FE27_C2_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw2 * FE27_C1_D100_Q421[0][0][0][i] * FE27_C0_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw7 * FE27_C1_D100_Q421[0][0][0][i] * FE27_C0_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw11 * FE27_C1_D100_Q421[0][0][0][i] * FE27_C1_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw12 * FE27_C1_D100_Q421[0][0][0][i] * FE27_C1_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw13 * FE27_C1_D100_Q421[0][0][0][i] * FE27_C2_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw14 * FE27_C1_D100_Q421[0][0][0][i] * FE27_C2_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw3 * FE27_C1_D001_Q421[0][0][0][i] * FE27_C0_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw8 * FE27_C1_D001_Q421[0][0][0][i] * FE27_C0_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw12 * FE27_C1_D001_Q421[0][0][0][i] * FE27_C1_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw15 * FE27_C1_D001_Q421[0][0][0][i] * FE27_C1_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw16 * FE27_C1_D001_Q421[0][0][0][i] * FE27_C2_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw17 * FE27_C1_D001_Q421[0][0][0][i] * FE27_C2_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw4 * FE27_C2_D100_Q421[0][0][0][i] * FE27_C0_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw9 * FE27_C2_D100_Q421[0][0][0][i] * FE27_C0_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw13 * FE27_C2_D100_Q421[0][0][0][i] * FE27_C1_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw16 * FE27_C2_D100_Q421[0][0][0][i] * FE27_C1_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw18 * FE27_C2_D100_Q421[0][0][0][i] * FE27_C2_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw19 * FE27_C2_D100_Q421[0][0][0][i] * FE27_C2_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw5 * FE27_C2_D010_Q421[0][0][0][i] * FE27_C0_D010_Q421[0][0][0][j];
        A[6 * i + j] += fw10 * FE27_C2_D010_Q421[0][0][0][i] * FE27_C0_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw14 * FE27_C2_D010_Q421[0][0][0][i] * FE27_C1_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw17 * FE27_C2_D010_Q421[0][0][0][i] * FE27_C1_D001_Q421[0][0][0][j];
        A[6 * i + j] += fw19 * FE27_C2_D010_Q421[0][0][0][i] * FE27_C2_D100_Q421[0][0][0][j];
        A[6 * i + j] += fw20 * FE27_C2_D010_Q421[0][0][0][i] * FE27_C2_D010_Q421[0][0][0][j];
      }
    }
  }
}

ufc_integral integral_cell_otherwise_2af0ba280175e3004e2c7b59d02851fa183ce88d = {.enabled_coefficients = NULL,
                                                                                 .tabulate_tensor = tabulate_tensor_integral_cell_otherwise_2af0ba280175e3004e2c7b59d02851fa183ce88d,
                                                                                 .needs_transformation_data = 1};

// End of code for integral integral_cell_otherwise_2af0ba280175e3004e2c7b59d02851fa183ce88d

// Code for form form_2af0ba280175e3004e2c7b59d02851fa183ce88d

ufc_dofmap *dofmaps_form_2af0ba280175e3004e2c7b59d02851fa183ce88d[2] = {&dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353,
                                                                        &dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353};
ufc_finite_element *finite_elements_form_2af0ba280175e3004e2c7b59d02851fa183ce88d[2] = {&element_7a6f94d9f714280d462314e33f6c4b34aa230353,
                                                                                        &element_7a6f94d9f714280d462314e33f6c4b34aa230353};

// Return a list of the coefficient names.
const char **coefficient_name_form_2af0ba280175e3004e2c7b59d02851fa183ce88d(void) { return NULL; }

// Return a list of the constant names.
const char **constant_name_form_2af0ba280175e3004e2c7b59d02851fa183ce88d(void) { return NULL; }

int *integral_ids_form_2af0ba280175e3004e2c7b59d02851fa183ce88d(ufc_integral_type integral_type)
{
  static int integral_ids_cell_form_2af0ba280175e3004e2c7b59d02851fa183ce88d[1] = {-1};
  switch (integral_type)
  {
  case cell:
    return integral_ids_cell_form_2af0ba280175e3004e2c7b59d02851fa183ce88d;
  default:
    return NULL;
  }
}

int num_integrals_form_2af0ba280175e3004e2c7b59d02851fa183ce88d(ufc_integral_type integral_type)
{
  switch (integral_type)
  {
  case cell:
    return 1;
  case interior_facet:
    return 0;
  case exterior_facet:
    return 0;
  default:
    return 0;
  }
}

ufc_integral **
integrals_form_2af0ba280175e3004e2c7b59d02851fa183ce88d(ufc_integral_type integral_type)
{
  static ufc_integral *integrals_cell_form_2af0ba280175e3004e2c7b59d02851fa183ce88d[1] = {&integral_cell_otherwise_2af0ba280175e3004e2c7b59d02851fa183ce88d};
  switch (integral_type)
  {
  case cell:
    return integrals_cell_form_2af0ba280175e3004e2c7b59d02851fa183ce88d;
  default:
    return NULL;
  }
}

ufc_form form_2af0ba280175e3004e2c7b59d02851fa183ce88d = {

    .signature = "82513d1151e86c6882d2e0ea04ef9d5ac2d83630887cd5dc91abe22e684793ea0f7ff4e84db0f1666"
                 "64724f61519c82fb28e47e5f0061caf8464062d1ed4e753",
    .rank = 2,
    .num_coefficients = 0,
    .num_constants = 0,
    .original_coefficient_position = NULL,

    .coefficient_name_map = coefficient_name_form_2af0ba280175e3004e2c7b59d02851fa183ce88d,
    .constant_name_map = constant_name_form_2af0ba280175e3004e2c7b59d02851fa183ce88d,

    .finite_elements = finite_elements_form_2af0ba280175e3004e2c7b59d02851fa183ce88d,
    .dofmaps = dofmaps_form_2af0ba280175e3004e2c7b59d02851fa183ce88d,

    .integral_ids = integral_ids_form_2af0ba280175e3004e2c7b59d02851fa183ce88d,
    .num_integrals = num_integrals_form_2af0ba280175e3004e2c7b59d02851fa183ce88d,

    .integrals = integrals_form_2af0ba280175e3004e2c7b59d02851fa183ce88d};

// Alias name
ufc_form *form_nedelec_a = &form_2af0ba280175e3004e2c7b59d02851fa183ce88d;

ufc_function_space *functionspace_form_nedelec_a(const char *function_name)
{
  static ufc_function_space functionspace_v = {.finite_element = &element_7a6f94d9f714280d462314e33f6c4b34aa230353,
                                               .dofmap = &dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353,
                                               .geometry_family = "Lagrange",
                                               .geometry_degree = 1};
  static ufc_function_space functionspace_u = {.finite_element = &element_7a6f94d9f714280d462314e33f6c4b34aa230353,
                                               .dofmap = &dofmap_7a6f94d9f714280d462314e33f6c4b34aa230353,
                                               .geometry_family = "Lagrange",
                                               .geometry_degree = 1};
  if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
  else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
  return NULL;
}

// End of code for form form_2af0ba280175e3004e2c7b59d02851fa183ce88d
