// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 0.1.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['lagrange.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4;

extern ufc_finite_element element_f98876eb49550d506341b4c1d32d16b6eec2e3aa;

extern ufc_dofmap dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4;

extern ufc_dofmap dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa;

extern ufc_integral integral_cell_otherwise_6169f1b8b02a174df5aa5b2135c811df067e58d5;

extern ufc_form form_6169f1b8b02a174df5aa5b2135c811df067e58d5;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_lagrange_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_lagrange_a(const char* function_name);

#ifdef __cplusplus
}
#endif
