// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 0.1.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['lagrange.ufl'],
//   'verbosity': 30,
//   'visualise': False}

typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4

ufc_finite_element element_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4
    = {.signature = "FiniteElement('Lagrange', tetrahedron, 1)",
       .cell_shape = tetrahedron,
       .topological_dimension = 3,
       .geometric_dimension = 3,
       .space_dimension = 4,
       .value_rank = 0,
       .value_shape = NULL,
       .value_size = 1,
       .reference_value_rank = 0,
       .reference_value_shape = NULL,
       .reference_value_size = 1,
       .degree = 1,
       .family = "Lagrange",
       .block_size = 1,

       .needs_transformation_data = 0,
       .interpolation_is_identity = 1,

       .num_sub_elements = 0,
       .sub_elements = NULL};

// End of code for element element_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4

// Code for element element_f98876eb49550d506341b4c1d32d16b6eec2e3aa

int value_shape_element_f98876eb49550d506341b4c1d32d16b6eec2e3aa[1] = {3};
int reference_value_shape_element_f98876eb49550d506341b4c1d32d16b6eec2e3aa[1] = {3};
ufc_finite_element* sub_elements_element_f98876eb49550d506341b4c1d32d16b6eec2e3aa[3]
    = {&element_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4,
       &element_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4,
       &element_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4};

ufc_finite_element element_f98876eb49550d506341b4c1d32d16b6eec2e3aa = {
    .signature = "VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
    .cell_shape = tetrahedron,
    .topological_dimension = 3,
    .geometric_dimension = 3,
    .space_dimension = 12,
    .value_rank = 1,
    .value_shape = value_shape_element_f98876eb49550d506341b4c1d32d16b6eec2e3aa,
    .value_size = 3,
    .reference_value_rank = 1,
    .reference_value_shape = reference_value_shape_element_f98876eb49550d506341b4c1d32d16b6eec2e3aa,
    .reference_value_size = 3,
    .degree = 1,
    .family = "Lagrange",
    .block_size = 3,

    .needs_transformation_data = 0,
    .interpolation_is_identity = 1,

    .num_sub_elements = 3,
    .sub_elements = sub_elements_element_f98876eb49550d506341b4c1d32d16b6eec2e3aa};

// End of code for element element_f98876eb49550d506341b4c1d32d16b6eec2e3aa

// Code for element element_450890e5777d4b17060829b5a7f6f9e88b058d15

ufc_finite_element element_450890e5777d4b17060829b5a7f6f9e88b058d15
    = {.signature = "FiniteElement('Lagrange', tetrahedron, 2)",
       .cell_shape = tetrahedron,
       .topological_dimension = 3,
       .geometric_dimension = 3,
       .space_dimension = 10,
       .value_rank = 0,
       .value_shape = NULL,
       .value_size = 1,
       .reference_value_rank = 0,
       .reference_value_shape = NULL,
       .reference_value_size = 1,
       .degree = 2,
       .family = "Lagrange",
       .block_size = 1,

       .needs_transformation_data = 0,
       .interpolation_is_identity = 1,

       .num_sub_elements = 0,
       .sub_elements = NULL};

// End of code for element element_450890e5777d4b17060829b5a7f6f9e88b058d15

// Code for dofmap dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4

void tabulate_entity_dofs_dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4(int* restrict dofs, int d,
                                                                          int i)
{
  switch (d)
  {
  case 0:
    switch (i)
    {
    case 0:
      dofs[0] = 0;
      break;
    case 1:
      dofs[0] = 1;
      break;
    case 2:
      dofs[0] = 2;
      break;
    case 3:
      dofs[0] = 3;
      break;
    }
    break;
  }
}

ufc_dofmap dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4
    = {.signature = "FFCX dofmap for FiniteElement('Lagrange', tetrahedron, 1)",
       .block_size = 1,
       .num_global_support_dofs = 0,
       .num_element_support_dofs = 4,
       .num_entity_dofs[0] = 1,
       .num_entity_dofs[1] = 0,
       .num_entity_dofs[2] = 0,
       .num_entity_dofs[3] = 0,
       .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4,
       .num_sub_dofmaps = 0,
       .sub_dofmaps = NULL};

// End of code for dofmap dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4

// Code for dofmap dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa

ufc_dofmap* sub_dofmaps_dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa[3]
    = {&dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4,
       &dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4,
       &dofmap_0867dce6bf5c3352d4f192cc2fe32c1c51c671a4};

void tabulate_entity_dofs_dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa(int* restrict dofs, int d,
                                                                          int i)
{
  switch (d)
  {
  case 0:
    switch (i)
    {
    case 0:
      dofs[0] = 0;
      break;
    case 1:
      dofs[0] = 1;
      break;
    case 2:
      dofs[0] = 2;
      break;
    case 3:
      dofs[0] = 3;
      break;
    }
    break;
  }
}

ufc_dofmap dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa = {
    .signature = "FFCX dofmap for VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
    .block_size = 3,
    .num_global_support_dofs = 0,
    .num_element_support_dofs = 4,
    .num_entity_dofs[0] = 1,
    .num_entity_dofs[1] = 0,
    .num_entity_dofs[2] = 0,
    .num_entity_dofs[3] = 0,
    .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa,
    .num_sub_dofmaps = 3,
    .sub_dofmaps = sub_dofmaps_dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa};

// End of code for dofmap dofmap_f98876eb49550d506341b4c1d32d16b6eec2e3aa

// Code for dofmap dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15

void tabulate_entity_dofs_dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15(int* restrict dofs, int d,
                                                                          int i)
{
  switch (d)
  {
  case 0:
    switch (i)
    {
    case 0:
      dofs[0] = 0;
      break;
    case 1:
      dofs[0] = 1;
      break;
    case 2:
      dofs[0] = 2;
      break;
    case 3:
      dofs[0] = 3;
      break;
    }
    break;
  case 1:
    switch (i)
    {
    case 0:
      dofs[0] = 4;
      break;
    case 1:
      dofs[0] = 5;
      break;
    case 2:
      dofs[0] = 6;
      break;
    case 3:
      dofs[0] = 7;
      break;
    case 4:
      dofs[0] = 8;
      break;
    case 5:
      dofs[0] = 9;
      break;
    }
    break;
  }
}

ufc_dofmap dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15
    = {.signature = "FFCX dofmap for FiniteElement('Lagrange', tetrahedron, 2)",
       .block_size = 1,
       .num_global_support_dofs = 0,
       .num_element_support_dofs = 10,
       .num_entity_dofs[0] = 1,
       .num_entity_dofs[1] = 1,
       .num_entity_dofs[2] = 0,
       .num_entity_dofs[3] = 0,
       .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15,
       .num_sub_dofmaps = 0,
       .sub_dofmaps = NULL};

// End of code for dofmap dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15

// Code for integral integral_cell_otherwise_999a26307e1ae9b391bee084d612ad9352f12a23

void tabulate_tensor_integral_cell_otherwise_999a26307e1ae9b391bee084d612ad9352f12a23(
    ufc_scalar_t* restrict A, const ufc_scalar_t* restrict w, const ufc_scalar_t* restrict c,
    const double* restrict coordinate_dofs, const int* restrict entity_local_index,
    const uint8_t* restrict quadrature_permutation, const uint32_t cell_permutation)
{
  // Quadrature rules
  static const double weights_175[5] = {-0.1333333333333333, 0.075, 0.075, 0.075, 0.075};
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE15_C0_D001_Q175[1][1][5][10]
      = {{{{0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, -1.0, -1.0},
           {0.3333333333333333, 0.0, 0.0, -0.3333333333333336, 0.6666666666666669, 2.0, 0.0, 0.0,
            -0.6666666666666666, -2.0},
           {0.3333333333333334, 0.0, 0.0, -0.3333333333333335, 2.0, 0.6666666666666672, 0.0, 0.0,
            -2.0, -0.6666666666666662},
           {0.3333333333333335, 0.0, 0.0, 1.0, 0.6666666666666669, 0.6666666666666667, 0.0,
            -1.333333333333333, -0.6666666666666665, -0.6666666666666665},
           {-1.0, 0.0, 0.0, -0.3333333333333335, 0.666666666666667, 0.6666666666666667, 0.0,
            1.333333333333334, -0.6666666666666666, -0.6666666666666664}}}};
  static const double FE15_C0_D010_Q175[1][1][5][10]
      = {{{{0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, -1.0, 0.0, -1.0},
           {0.3333333333333333, 0.0, -0.3333333333333336, 0.0, 0.6666666666666665, 0.0, 2.0,
            -0.6666666666666664, 0.0, -2.0},
           {0.3333333333333334, 0.0, 1.0, 0.0, 0.666666666666667, 0.0, 0.6666666666666671,
            -0.6666666666666663, -1.333333333333333, -0.6666666666666662},
           {0.3333333333333335, 0.0, -0.3333333333333334, 0.0, 2.0, 0.0, 0.6666666666666667, -2.0,
            0.0, -0.6666666666666665},
           {-1.0, 0.0, -0.3333333333333334, 0.0, 0.6666666666666663, 0.0, 0.6666666666666663,
            -0.6666666666666669, 1.333333333333334, -0.6666666666666667}}}};
  static const double FE15_C0_D100_Q175[1][1][5][10]
      = {{{{0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, -1.0, -1.0, 0.0},
           {0.3333333333333334, 1.0, 0.0, 0.0, 0.0, 0.6666666666666665, 0.6666666666666665,
            -0.6666666666666665, -0.6666666666666665, -1.333333333333333},
           {0.3333333333333334, -0.3333333333333336, 0.0, 0.0, 0.0, 0.666666666666667, 2.0,
            -0.6666666666666663, -2.0, 0.0},
           {0.3333333333333335, -0.3333333333333335, 0.0, 0.0, 0.0, 2.0, 0.6666666666666666, -2.0,
            -0.6666666666666665, 0.0},
           {-1.0, -0.3333333333333338, 0.0, 0.0, 0.0, 0.6666666666666667, 0.6666666666666665,
            -0.6666666666666667, -0.6666666666666665, 1.333333333333334}}}};
  static const double FE9_C0_D001_Q175[1][1][1][4] = {{{{-1.0, 0.0, 0.0, 1.0}}}};
  static const double FE9_C0_D010_Q175[1][1][1][4] = {{{{-1.0, 0.0, 1.0, 0.0}}}};
  static const double FE9_C0_D100_Q175[1][1][1][4] = {{{{-1.0, 1.0, 0.0, 0.0}}}};
  // Quadrature loop independent computations for quadrature rule 175
  const double J_c4 = coordinate_dofs[1] * FE9_C0_D010_Q175[0][0][0][0]
                      + coordinate_dofs[4] * FE9_C0_D010_Q175[0][0][0][1]
                      + coordinate_dofs[7] * FE9_C0_D010_Q175[0][0][0][2]
                      + coordinate_dofs[10] * FE9_C0_D010_Q175[0][0][0][3];
  const double J_c8 = coordinate_dofs[2] * FE9_C0_D001_Q175[0][0][0][0]
                      + coordinate_dofs[5] * FE9_C0_D001_Q175[0][0][0][1]
                      + coordinate_dofs[8] * FE9_C0_D001_Q175[0][0][0][2]
                      + coordinate_dofs[11] * FE9_C0_D001_Q175[0][0][0][3];
  const double J_c5 = coordinate_dofs[1] * FE9_C0_D001_Q175[0][0][0][0]
                      + coordinate_dofs[4] * FE9_C0_D001_Q175[0][0][0][1]
                      + coordinate_dofs[7] * FE9_C0_D001_Q175[0][0][0][2]
                      + coordinate_dofs[10] * FE9_C0_D001_Q175[0][0][0][3];
  const double J_c7 = coordinate_dofs[2] * FE9_C0_D010_Q175[0][0][0][0]
                      + coordinate_dofs[5] * FE9_C0_D010_Q175[0][0][0][1]
                      + coordinate_dofs[8] * FE9_C0_D010_Q175[0][0][0][2]
                      + coordinate_dofs[11] * FE9_C0_D010_Q175[0][0][0][3];
  const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Q175[0][0][0][0]
                      + coordinate_dofs[3] * FE9_C0_D100_Q175[0][0][0][1]
                      + coordinate_dofs[6] * FE9_C0_D100_Q175[0][0][0][2]
                      + coordinate_dofs[9] * FE9_C0_D100_Q175[0][0][0][3];
  const double J_c1 = coordinate_dofs[0] * FE9_C0_D010_Q175[0][0][0][0]
                      + coordinate_dofs[3] * FE9_C0_D010_Q175[0][0][0][1]
                      + coordinate_dofs[6] * FE9_C0_D010_Q175[0][0][0][2]
                      + coordinate_dofs[9] * FE9_C0_D010_Q175[0][0][0][3];
  const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Q175[0][0][0][0]
                      + coordinate_dofs[5] * FE9_C0_D100_Q175[0][0][0][1]
                      + coordinate_dofs[8] * FE9_C0_D100_Q175[0][0][0][2]
                      + coordinate_dofs[11] * FE9_C0_D100_Q175[0][0][0][3];
  const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Q175[0][0][0][0]
                      + coordinate_dofs[4] * FE9_C0_D100_Q175[0][0][0][1]
                      + coordinate_dofs[7] * FE9_C0_D100_Q175[0][0][0][2]
                      + coordinate_dofs[10] * FE9_C0_D100_Q175[0][0][0][3];
  const double J_c2 = coordinate_dofs[0] * FE9_C0_D001_Q175[0][0][0][0]
                      + coordinate_dofs[3] * FE9_C0_D001_Q175[0][0][0][1]
                      + coordinate_dofs[6] * FE9_C0_D001_Q175[0][0][0][2]
                      + coordinate_dofs[9] * FE9_C0_D001_Q175[0][0][0][3];
  ufc_scalar_t sp_175[80];
  sp_175[0] = J_c4 * J_c8;
  sp_175[1] = J_c5 * J_c7;
  sp_175[2] = sp_175[0] + -1 * sp_175[1];
  sp_175[3] = J_c0 * sp_175[2];
  sp_175[4] = J_c5 * J_c6;
  sp_175[5] = J_c3 * J_c8;
  sp_175[6] = sp_175[4] + -1 * sp_175[5];
  sp_175[7] = J_c1 * sp_175[6];
  sp_175[8] = sp_175[3] + sp_175[7];
  sp_175[9] = J_c3 * J_c7;
  sp_175[10] = J_c4 * J_c6;
  sp_175[11] = sp_175[9] + -1 * sp_175[10];
  sp_175[12] = J_c2 * sp_175[11];
  sp_175[13] = sp_175[8] + sp_175[12];
  sp_175[14] = sp_175[2] / sp_175[13];
  sp_175[15] = J_c3 * (-1 * J_c8);
  sp_175[16] = sp_175[4] + sp_175[15];
  sp_175[17] = sp_175[16] / sp_175[13];
  sp_175[18] = sp_175[11] / sp_175[13];
  sp_175[19] = sp_175[14] * sp_175[14];
  sp_175[20] = sp_175[14] * sp_175[17];
  sp_175[21] = sp_175[18] * sp_175[14];
  sp_175[22] = sp_175[17] * sp_175[17];
  sp_175[23] = sp_175[18] * sp_175[17];
  sp_175[24] = sp_175[18] * sp_175[18];
  sp_175[25] = J_c2 * J_c7;
  sp_175[26] = J_c8 * (-1 * J_c1);
  sp_175[27] = sp_175[25] + sp_175[26];
  sp_175[28] = sp_175[27] / sp_175[13];
  sp_175[29] = J_c0 * J_c8;
  sp_175[30] = J_c6 * (-1 * J_c2);
  sp_175[31] = sp_175[29] + sp_175[30];
  sp_175[32] = sp_175[31] / sp_175[13];
  sp_175[33] = J_c1 * J_c6;
  sp_175[34] = J_c0 * J_c7;
  sp_175[35] = sp_175[33] + -1 * sp_175[34];
  sp_175[36] = sp_175[35] / sp_175[13];
  sp_175[37] = sp_175[28] * sp_175[28];
  sp_175[38] = sp_175[28] * sp_175[32];
  sp_175[39] = sp_175[28] * sp_175[36];
  sp_175[40] = sp_175[32] * sp_175[32];
  sp_175[41] = sp_175[32] * sp_175[36];
  sp_175[42] = sp_175[36] * sp_175[36];
  sp_175[43] = sp_175[37] + sp_175[19];
  sp_175[44] = sp_175[38] + sp_175[20];
  sp_175[45] = sp_175[39] + sp_175[21];
  sp_175[46] = sp_175[40] + sp_175[22];
  sp_175[47] = sp_175[41] + sp_175[23];
  sp_175[48] = sp_175[24] + sp_175[42];
  sp_175[49] = J_c1 * J_c5;
  sp_175[50] = J_c2 * J_c4;
  sp_175[51] = sp_175[49] + -1 * sp_175[50];
  sp_175[52] = sp_175[51] / sp_175[13];
  sp_175[53] = J_c2 * J_c3;
  sp_175[54] = J_c0 * J_c5;
  sp_175[55] = sp_175[53] + -1 * sp_175[54];
  sp_175[56] = sp_175[55] / sp_175[13];
  sp_175[57] = J_c0 * J_c4;
  sp_175[58] = J_c1 * J_c3;
  sp_175[59] = sp_175[57] + -1 * sp_175[58];
  sp_175[60] = sp_175[59] / sp_175[13];
  sp_175[61] = sp_175[52] * sp_175[52];
  sp_175[62] = sp_175[52] * sp_175[56];
  sp_175[63] = sp_175[60] * sp_175[52];
  sp_175[64] = sp_175[56] * sp_175[56];
  sp_175[65] = sp_175[60] * sp_175[56];
  sp_175[66] = sp_175[60] * sp_175[60];
  sp_175[67] = sp_175[43] + sp_175[61];
  sp_175[68] = sp_175[44] + sp_175[62];
  sp_175[69] = sp_175[45] + sp_175[63];
  sp_175[70] = sp_175[46] + sp_175[64];
  sp_175[71] = sp_175[47] + sp_175[65];
  sp_175[72] = sp_175[48] + sp_175[66];
  sp_175[73] = fabs(sp_175[13]);
  sp_175[74] = sp_175[67] * sp_175[73];
  sp_175[75] = sp_175[68] * sp_175[73];
  sp_175[76] = sp_175[69] * sp_175[73];
  sp_175[77] = sp_175[70] * sp_175[73];
  sp_175[78] = sp_175[71] * sp_175[73];
  sp_175[79] = sp_175[72] * sp_175[73];
  for (int iq = 0; iq < 5; ++iq)
  {
    const ufc_scalar_t fw0 = sp_175[74] * weights_175[iq];
    const ufc_scalar_t fw1 = sp_175[75] * weights_175[iq];
    const ufc_scalar_t fw2 = sp_175[76] * weights_175[iq];
    const ufc_scalar_t fw3 = sp_175[77] * weights_175[iq];
    const ufc_scalar_t fw4 = sp_175[78] * weights_175[iq];
    const ufc_scalar_t fw5 = sp_175[79] * weights_175[iq];
    for (int i = 0; i < 10; ++i)
      for (int j = 0; j < 10; ++j)
      {
        A[10 * i + j] += fw0 * FE15_C0_D100_Q175[0][0][iq][i] * FE15_C0_D100_Q175[0][0][iq][j];
        A[10 * i + j] += fw1 * FE15_C0_D100_Q175[0][0][iq][i] * FE15_C0_D010_Q175[0][0][iq][j];
        A[10 * i + j] += fw2 * FE15_C0_D100_Q175[0][0][iq][i] * FE15_C0_D001_Q175[0][0][iq][j];
        A[10 * i + j] += fw1 * FE15_C0_D010_Q175[0][0][iq][i] * FE15_C0_D100_Q175[0][0][iq][j];
        A[10 * i + j] += fw3 * FE15_C0_D010_Q175[0][0][iq][i] * FE15_C0_D010_Q175[0][0][iq][j];
        A[10 * i + j] += fw4 * FE15_C0_D010_Q175[0][0][iq][i] * FE15_C0_D001_Q175[0][0][iq][j];
        A[10 * i + j] += fw2 * FE15_C0_D001_Q175[0][0][iq][i] * FE15_C0_D100_Q175[0][0][iq][j];
        A[10 * i + j] += fw4 * FE15_C0_D001_Q175[0][0][iq][i] * FE15_C0_D010_Q175[0][0][iq][j];
        A[10 * i + j] += fw5 * FE15_C0_D001_Q175[0][0][iq][i] * FE15_C0_D001_Q175[0][0][iq][j];
      }
  }
}

ufc_integral integral_cell_otherwise_999a26307e1ae9b391bee084d612ad9352f12a23
    = {.enabled_coefficients = NULL,
       .tabulate_tensor
       = tabulate_tensor_integral_cell_otherwise_999a26307e1ae9b391bee084d612ad9352f12a23,
       .needs_transformation_data = 0};

// End of code for integral integral_cell_otherwise_999a26307e1ae9b391bee084d612ad9352f12a23

// Code for form form_999a26307e1ae9b391bee084d612ad9352f12a23

ufc_dofmap* dofmaps_form_999a26307e1ae9b391bee084d612ad9352f12a23[2]
    = {&dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15,
       &dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15};
ufc_finite_element* finite_elements_form_999a26307e1ae9b391bee084d612ad9352f12a23[2]
    = {&element_450890e5777d4b17060829b5a7f6f9e88b058d15,
       &element_450890e5777d4b17060829b5a7f6f9e88b058d15};

// Return a list of the coefficient names.
const char** coefficient_name_form_999a26307e1ae9b391bee084d612ad9352f12a23(void) { return NULL; }

// Return a list of the constant names.
const char** constant_name_form_999a26307e1ae9b391bee084d612ad9352f12a23(void) { return NULL; }

int* integral_ids_form_999a26307e1ae9b391bee084d612ad9352f12a23(ufc_integral_type integral_type)
{
  static int integral_ids_cell_form_999a26307e1ae9b391bee084d612ad9352f12a23[1] = {-1};
  switch (integral_type)
  {
  case cell:
    return integral_ids_cell_form_999a26307e1ae9b391bee084d612ad9352f12a23;
  default:
    return NULL;
  }
}

int num_integrals_form_999a26307e1ae9b391bee084d612ad9352f12a23(ufc_integral_type integral_type)
{
  switch (integral_type)
  {
  case cell:
    return 1;
  case interior_facet:
    return 0;
  case exterior_facet:
    return 0;
  default:
    return 0;
  }
}

ufc_integral**
integrals_form_999a26307e1ae9b391bee084d612ad9352f12a23(ufc_integral_type integral_type)
{
  static ufc_integral* integrals_cell_form_999a26307e1ae9b391bee084d612ad9352f12a23[1]
      = {&integral_cell_otherwise_999a26307e1ae9b391bee084d612ad9352f12a23};
  switch (integral_type)
  {
  case cell:
    return integrals_cell_form_999a26307e1ae9b391bee084d612ad9352f12a23;
  default:
    return NULL;
  }
}

ufc_form form_999a26307e1ae9b391bee084d612ad9352f12a23 = {

    .signature = "e7bf27418babfa8941abd8759e6ce72688b850c2859a5e7afaab8e4a68f8eca8b0463f954ef03d2da"
                 "66a9def4bbfc457b2d3d0b2db07f2cb94fd9079c24e97cf",
    .rank = 2,
    .num_coefficients = 0,
    .num_constants = 0,
    .original_coefficient_position = NULL,

    .coefficient_name_map = coefficient_name_form_999a26307e1ae9b391bee084d612ad9352f12a23,
    .constant_name_map = constant_name_form_999a26307e1ae9b391bee084d612ad9352f12a23,

    .finite_elements = finite_elements_form_999a26307e1ae9b391bee084d612ad9352f12a23,
    .dofmaps = dofmaps_form_999a26307e1ae9b391bee084d612ad9352f12a23,

    .integral_ids = integral_ids_form_999a26307e1ae9b391bee084d612ad9352f12a23,
    .num_integrals = num_integrals_form_999a26307e1ae9b391bee084d612ad9352f12a23,

    .integrals = integrals_form_999a26307e1ae9b391bee084d612ad9352f12a23};

// Alias name
ufc_form* form_lagrange_a = &form_999a26307e1ae9b391bee084d612ad9352f12a23;

ufc_function_space* functionspace_form_lagrange_a(const char* function_name)
{
  static ufc_function_space functionspace_v
      = {.finite_element = &element_450890e5777d4b17060829b5a7f6f9e88b058d15,
         .dofmap = &dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15,
         .geometry_family = "Lagrange",
         .geometry_degree = 1};
  static ufc_function_space functionspace_u
      = {.finite_element = &element_450890e5777d4b17060829b5a7f6f9e88b058d15,
         .dofmap = &dofmap_450890e5777d4b17060829b5a7f6f9e88b058d15,
         .geometry_family = "Lagrange",
         .geometry_degree = 1};
  if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
  else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
  return NULL;
}

// End of code for form form_999a26307e1ae9b391bee084d612ad9352f12a23
